sandbox:
  domains:
    - model: "baas"
      onbehalf: "customers"
      api: "accounts"
    - model: "baas"
      onbehalf: "customers"
      api: "payments"
    - model: "baas"
      onbehalf: "customers"
      api: "accounts"
    - model: "baas"
      onbehalf: "customers"
      api: "payments"
    - model: "baas"
      onbehalf: "customers"
      api: "products"
    - model: "baas"
      onbehalf: "customers"
      api: "onboarding"
    - model: "baas"
      onbehalf: "customers"
      api: "cards"
    - model: "baas"
      onbehalf: "customers"
      api: "credits"
    - model: "baas"
      onbehalf: "customers"
      api: "summary"
    - model: "baas"
      onbehalf: "customers"
      api: "MoneyTransfers"
    - model: "baas"
      onbehalf: "customers"
      api: "customers"
    - model: "baas"
      onbehalf: "customers"
      api: "services"
    - model: "baas"
      onbehalf: "customers"
      api: "investments"
    - model: "iaas"
      onbehalf: "customers"
      api: "summary"
    - model: "iaas"
      onbehalf: "customers"
      api: "policies"
    - model: "tools"
      onbehalf: "apis"
      api: "publishers"
    - model: "tools"
      onbehalf: "apis"
      api: "sandbox"
    - model: "tools"
      onbehalf: "apis"
      api: "syntax"
    - model: "tools"
      onbehalf: "apis"
      api: "codegenerator"
    - model: "tools"
      onbehalf: "apis"
      api: "api-manager"
    - model: "tools"
      onbehalf: "apis"
      api: "api-deployment"
    - model: "baas"
      onbehalf: "systems"
      api: "accounts"
    - model: "baas"
      onbehalf: "systems"
      api: "customers"
    - model: "baas"
      onbehalf: "systems"
      api: "executives"
